### ISSUE TITLE
Make Menuconfig Settings? And how to use this without the addon screen?

### ISSUE THREAD

**Issue by Declan0811** [rpanfili/sk200#1]
So, I've taken an interest in this, and I am extremely thankful that you released this, but I cannot figure out what settings to use in the menuconfig setup. Also, can I use this without buying the larger screen? Thanks!

**Comment by rpanfili** [comment]
Hi Declan, I'm not sure that I got your question but if you are talking about flashing the firmware on the skr you should select the `lcp1768` processor for the v1.3, `lcp1769` for the (1.4) turbo version. The easiest way is to compile everything with `make`, copy the `.bin` from the `klipper/out/` directory into the SD card and just reboot. With klipper the screen is not required so feel free to remove the `[display]` section from you configuration (https://github.com/rpanfili/sk200/blob/master/config/display/reprap-12864.cfg)

**Comment by Declan0811** [comment]
Ok, so that really helps, but to help clarify, my question was what settings to use for this menu? Such as the microcontroller architecture, processor model, as well as any other settings? Thanks!
![image](https://user-images.githubusercontent.com/58826291/140811257-eb521183-ea69-434f-bff6-bbecfd78fa37.png)

**Comment by Declan0811** [comment]
Figured out the proper settings!
