### ISSUE TITLE
Upon Introduction of Printer.cfg Issues Appear

### ISSUE THREAD

**Issue by Declan0811** [rpanfili/sk200#2]
So, I have just input the correct printer.cfg and everything linking to sk200, but I am all of a sudden hit with a bunch of errors. I'll try to list them in the order below.
- Option 'color_order_grb' is not valid in section 'neopixel fysetc_mini12864'
- Option 'position_endstop' is not valid in section 'stepper_z'
 The deletion of both of these lines solves the issues, but I don't know if they are important. Can I just delete them, or is there some other fix? Thanks!

**Comment by rpanfili** [comment]
Since you are not using any display you should not import the `mini-12864.cfg` as you are probably doing in `display.cfg`.
Talking about the `stepper_z` Idk, if you are not using a physical endstop but just a probe or something like that should be fine. If you are able to home Z you will know :)

**Comment by Declan0811** [comment]
Well, if I could use the standard screen I would, but if not thats fine. Also, I am using a physical z switch stopper, so I dont know what to do about that. And now, I'm trying to figure out how to connect the pi to the printer :/
